#' This is the signature matrix generated by tha abis authors
#'
#' It is internally used by run_abis() but can be exported to allow modifications.
#'
#' @name abis_signature
#' @docType data
#'
#' @references \url{https://github.com/giannimonaco/ABIS}
"abis_signature"
